name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.6.2
  intl: ^0.20.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/cinemapedia.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true



flutter:
  uses-material-design: true

  assets:
    - .env
    - ./assets/loaders/bottle-loader.gif
